# Generated by Django 3.1.6 on 2021-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordem',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterField(
            model_name='ordem',
            name='finalizacao_OS',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
