# Generated by Django 3.1.6 on 2021-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0002_auto_20210215_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='AN',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='HE',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='HE_percentual',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='HT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='QTD',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='adicional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='custo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='deslocamento_quilometragem',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='outros',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='pedagio',
            field=models.FloatField(default=0),
        ),
    ]
