# Generated by Django 3.1.7 on 2021-02-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasteceiros',
            name='tipo',
            field=models.CharField(blank=True, choices=[('despesa', 'Despesa'), ('servico', 'Serviço')], max_length=150, null=True),
        ),
    ]
