# Generated by Django 3.1.7 on 2021-02-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0004_auto_20210222_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasteceiros',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='desloc_km',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='pedagio',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
