# Generated by Django 3.1.7 on 2021-02-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0005_auto_20210222_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasteceiros',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='comprasteceiros',
            name='desloc_km',
        ),
    ]
