# Generated by Django 3.1.7 on 2021-02-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0006_auto_20210222_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasteceiros',
            name='desloc_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
