# Generated by Django 3.1.7 on 2021-02-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0007_comprasteceiros_desloc_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasteceiros',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comprasteceiros',
            name='tipo',
            field=models.CharField(blank=True, choices=[('despesa', 'Despesa'), ('servico', 'Serviço')], max_length=150, null=True),
        ),
    ]
