# Generated by Django 3.1.7 on 2021-02-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_terceiros', '0008_auto_20210222_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasteceiros',
            name='custo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
