# Generated by Django 3.1.7 on 2021-02-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0015_auto_20210221_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.ManyToManyField(to='cadastro.Servico')),
            ],
            options={
                'verbose_name': 'Venda ',
                'verbose_name_plural': 'Vendas ',
            },
        ),
    ]
