# Generated by Django 3.1.6 on 2021-02-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.CharField(max_length=10)),
                ('centro_de_custo', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('prazo', models.IntegerField()),
                ('grupo', models.CharField(choices=[('E', 'Externo'), ('I', 'Interno')], max_length=100)),
                ('metodo_de_cobranca', models.CharField(choices=[('diaria', 'Diária'), ('horas', 'Horas'), ('quantidade', 'Quantidade'), ('adicional', 'Adicional'), ('md -50 / dc +50', 'MD -50% / DC +50%')], max_length=100)),
                ('qualificacao', models.CharField(max_length=100)),
                ('atribuicao', models.CharField(choices=[('exe', 'Executante'), ('resp', 'Responsável')], max_length=100)),
            ],
        ),
    ]
