# Generated by Django 3.1.6 on 2021-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('kras', 'Kras'), ('terceiro', 'Terceiro')], max_length=100)),
                ('metodo_cobranca', models.CharField(blank=True, choices=[('diaria', 'Diária'), ('horas', 'Horas')], max_length=100, null=True)),
            ],
        ),
    ]
