# Generated by Django 3.1.7 on 2021-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20210215_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='usn2s4',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
