# Generated by Django 3.1.7 on 2021-02-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_colaborador_usn2s4'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='crea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='if_n1_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
