# Generated by Django 3.1.7 on 2021-02-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_auto_20210219_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='if_n1_at',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='usn2s4',
        ),
        migrations.CreateModel(
            name='AtribuicaoDeQualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.colaborador')),
                ('qualificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.qualificacao')),
            ],
            options={
                'verbose_name': 'Qualificação do Colaborador',
                'verbose_name_plural': 'Qualificações do Colaborador',
            },
        ),
    ]
