# Generated by Django 3.1.7 on 2021-02-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20210220_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='crea',
        ),
    ]
