# Generated by Django 3.1.7 on 2021-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_remove_colaborador_crea'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='valor_diaria',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
