# Generated by Django 3.1.7 on 2021-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_auto_20210221_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='agencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='banco',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cnh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='conta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('debito_conta', 'Débito')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
