# Generated by Django 3.1.7 on 2021-02-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_auto_20210221_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrocusto', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao_compras', models.CharField(blank=True, max_length=100, null=True)),
                ('unidade', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
