# Generated by Django 3.1.7 on 2021-02-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0015_auto_20210221_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
            ],
            options={
                'verbose_name': 'Proposta de Serviço',
                'verbose_name_plural': 'Propostas de Serviço',
            },
        ),
    ]
