# Generated by Django 3.1.7 on 2021-02-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210228_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='custo_pedido',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True),
        ),
    ]
