# Generated by Django 3.1.7 on 2021-02-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_compras'),
        ('compras', '0003_compras_custo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='descricao',
            field=models.ManyToManyField(blank=True, null=True, to='cadastro.Compras'),
        ),
    ]
